### ISSUE TITLE
Use Maven build tool

### ISSUE THREAD

**Issue by pitzzahh** [soybean15/CScreen#1]
Use Maven build tool.

benefits:
- dependency management and versioning
- able to upload to maven central repository
   instead of providing a jar file in your github repo, those who use maven can automatically download the jar file by providing a dependency

for example in my github repo [util-classes](https://github.com/pitzzahh/util-classes) you can use the jar file by providing the dependency in the pom.xml file

```maven
<dependencies>
    <!-- other dependencies are there -->
    <dependency>
        <groupId>io.github.pitzzahh</groupId>
        <artifactId>util-classes</artifactId>
        <version>1.0.4</version>
    </dependency>
    <!-- other dependencies are there -->
</dependencies>
```

**Comment by pitzzahh** [comment]
If you know maven
follow the instructions here
[instructions](https://central.sonatype.org/publish/)

**Comment by soybean15** [comment]
> If you know maven follow the instructions here [instructions](https://central.sonatype.org/publish/)

oh, cge check ko, thank you

**Comment by pitzzahh** [comment]
PR requested: https://github.com/soybean15/CScreen/pull/3
